### ISSUE TITLE
일부 화면에 대해 Router Path를 다시 작성해야됨!!

### ISSUE THREAD

**Issue by yayongi** [yayongi/idosoft#39]
화면 이동할 때 왼쪽 메뉴가 활성화되도록 하려면
목록에서 이동하는 하위 화면의 URL은 목록의 URL을 포함해야된다.

* 좋은예) 
자원관리목록 : /resource
자원관리등록 : /resource/regist    
         => resource를 포함하므로 자원관리목록 메뉴로 인식됨

* 나쁜예)
사원관리 목록 : /member/memberlist
사원관리 등록 : /member/memberreg   
          => 등록이 목록을 포함하고 있지 않으므로 같은 메뉴로 인식되지 않음.

**Comment by KangSeongWoo** [comment]
나쁜예.... 수정 조치 하였습니다...
